"""
dcf.py — Discounted Cash Flow Valuation

Purpose:
- Take Free Cash Flow projections generated by three_statement.py
- Apply a discount rate (WACC)
- Compute Present Value (PV) of each projected FCF
- Add Terminal Value (TV)
- Return enterprise value (EV), and optionally equity value/share price

Inputs:
- company_id
- model_version (optional)
- DB session (to load snapshot or working assumptions)
- Must call run_three_statement() first to obtain projected FCFs

Outputs (JSON-serializable):
{
  "fcf": [...],           # projected free cash flows
  "discount_factors": [...],
  "pv_fcf": [...],
  "terminal_value": float,
  "enterprise_value": float,
  "equity_value": float | None,
  "implied_share_price": float | None
}

This module does NOT:
- Pull historicals directly
- Produce Excel output
"""

from sqlalchemy.orm import Session
from typing import Dict, Any

from app.services.modeling.three_statement import run_three_statement
from app.models.valuation_model import ValuationModel
from app.models.model_snapshot import ModelSnapshot


def run_dcf(company_id: int,
            model_version: str | None,
            db: Session) -> Dict[str, Any]:
    """
    Main entrypoint for DCF valuation.

    High-Level Steps:
    1. Call run_three_statement() → get projected free cash flows.
    2. Load WACC + terminal value inputs:
        - If model_version provided → from ModelSnapshot
        - Else → from ValuationModel (current working assumptions)
    3. Apply discount factors:
           PV_FCF[t] = FCF[t] / (1 + WACC)^(t+1)
    4. Compute Terminal Value:
           TV = FCF[last] * (1 + g) / (WACC - g)
       or optionally:
           TV = EBIT * Exit Multiple (future extension)
    5. Enterprise Value = sum(PV_FCF) + PV(TV)
    6. If desired → compute equity value:
           EV - Debt + Cash
    7. Optionally compute implied share price:
           EquityValue / SharesOutstanding

    TODO:
    - Implement discounting math after projection model is in place.
    - Add support for exit multiple terminal value alternative.
    - Add optional equity bridge (Cash & Debt from Balance Sheet if available).
    """
    raise NotImplementedError("run_dcf() requires projected free cash flow inputs and WACC/terminal assumptions.")
