"""
dcf.py — Discounted Cash Flow Valuation

Purpose:
- Take Free Cash Flow projections generated by three_statement.py
- Apply a discount rate (WACC)
- Compute Present Value (PV) of each projected FCF
- Add Terminal Value (TV)
- Return enterprise value (EV), and optionally equity value/share price

Inputs (MVP - no database):
- projections: Dict from run_three_statement() containing free_cash_flow array
- assumptions: Dict with WACC, terminal_growth_rate, etc.

Outputs (JSON-serializable):
{
  "fcf": [...],           # projected free cash flows
  "discount_factors": [...],
  "pv_fcf": [...],
  "terminal_value": float,
  "pv_terminal_value": float,
  "enterprise_value": float,
  "equity_value": float | None,
  "implied_share_price": float | None
}

This module does NOT:
- Pull historicals directly
- Produce Excel output
"""

from typing import Dict, Any, List


def run_dcf(
    projections: Dict[str, Any],
    assumptions: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Main entrypoint for DCF valuation (MVP - no database).

    Args:
        projections: Output from run_three_statement() containing:
            - free_cash_flow: List[float]
            - periods: List[str]
        assumptions: Dict with keys:
            - wacc: float (weighted average cost of capital, e.g., 0.10 for 10%)
            - terminal_growth_rate: float (perpetual growth rate, e.g., 0.025 for 2.5%)
            - shares_outstanding: float | None (for share price calculation)
            - debt: float | None (for equity value calculation)
            - cash: float | None (for equity value calculation)

    Returns:
        Dictionary with DCF valuation results
    """
    fcf_list = projections.get("free_cash_flow", [])
    periods = projections.get("periods", [])
    
    if not fcf_list:
        raise ValueError("No free cash flow projections provided")

    # Extract assumptions with defaults
    wacc = assumptions.get("wacc", 0.10)  # 10% default
    terminal_growth = assumptions.get("terminal_growth_rate", 0.025)  # 2.5% default
    shares_outstanding = assumptions.get("shares_outstanding")
    debt = assumptions.get("debt", 0.0)
    cash = assumptions.get("cash", 0.0)

    # Validate WACC and terminal growth
    if wacc <= 0:
        raise ValueError("WACC must be positive")
    if terminal_growth >= wacc:
        raise ValueError("Terminal growth rate must be less than WACC")

    # Step 1: Calculate present value of each projected FCF
    pv_fcf: List[float] = []
    discount_factors: List[float] = []
    
    for i, fcf in enumerate(fcf_list):
        # Discount factor: 1 / (1 + WACC)^(period_number)
        # Period 1 is discounted by 1 year, period 2 by 2 years, etc.
        discount_factor = 1.0 / ((1 + wacc) ** (i + 1))
        discount_factors.append(discount_factor)
        
        pv = fcf * discount_factor
        pv_fcf.append(pv)

    # Step 2: Calculate Terminal Value
    # Using Gordon Growth Model: TV = FCF[last] * (1 + g) / (WACC - g)
    last_fcf = fcf_list[-1]
    terminal_value = last_fcf * (1 + terminal_growth) / (wacc - terminal_growth)

    # Step 3: Discount Terminal Value to present
    # TV is at end of projection period, so discount by number of periods
    num_periods = len(fcf_list)
    pv_terminal_value = terminal_value / ((1 + wacc) ** num_periods)

    # Step 4: Calculate Enterprise Value
    # EV = Sum of PV(FCF) + PV(Terminal Value)
    enterprise_value = sum(pv_fcf) + pv_terminal_value

    # Step 5: Calculate Equity Value (if balance sheet data available)
    equity_value = None
    implied_share_price = None
    
    if shares_outstanding is not None:
        # Equity Value = Enterprise Value - Debt + Cash
        equity_value = enterprise_value - debt + cash
        
        # Implied share price
        if shares_outstanding > 0:
            implied_share_price = equity_value / shares_outstanding

    return {
        "fcf": fcf_list,
        "discount_factors": discount_factors,
        "pv_fcf": pv_fcf,
        "terminal_value": terminal_value,
        "pv_terminal_value": pv_terminal_value,
        "enterprise_value": enterprise_value,
        "equity_value": equity_value,
        "implied_share_price": implied_share_price,
        "wacc": wacc,
        "terminal_growth_rate": terminal_growth,
    }
